
-- =====================================================================
-- (make sure you have completed part 1 and already connected to it)
-- Part 2: Create extensions, tables, indexes, triggers, and views
-- Run everything below while connected to the newly created database.
-- =====================================================================
BEGIN;

-- Required for the trigram GIN index used by mixed-language retrieval.
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- =====================================================================
-- Core knowledge-base schema
-- =====================================================================

-- =====================================================
-- Shared trigger function for UpdatedAt columns
-- =====================================================
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.UpdatedAt := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

-- =====================================================
-- 1. Document: one row per physical file
-- =====================================================
CREATE TABLE Document
(
    DocID              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    FullPath           VARCHAR(1200) NOT NULL,
    RelativePath       VARCHAR(1000),
    FolderPath         VARCHAR(1000),

    FolderLevel1       VARCHAR(255),
    FolderLevel2       VARCHAR(255),
    FolderLevel3       VARCHAR(255),
    FolderLevel4       VARCHAR(255),

    FileName           VARCHAR(500) NOT NULL,
    Extension          VARCHAR(30),

    FileSizeBytes      BIGINT,
    ModifiedTime       TIMESTAMP WITHOUT TIME ZONE,

    FileHashSHA256     CHAR(64),
    Metadata            JSONB,

    ParseStatus        VARCHAR(30) DEFAULT 'Pending',
    ParseTime          TIMESTAMP WITHOUT TIME ZONE,
    ErrorMessage       TEXT,

    CreatedAt          TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt          TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT UX_Document_FullPath UNIQUE (FullPath)
);

CREATE INDEX IX_Document_FileName      ON Document (FileName);
CREATE INDEX IX_Document_Extension     ON Document (Extension);
CREATE INDEX IX_Document_ParseStatus   ON Document (ParseStatus);
CREATE INDEX IX_Document_Folder1       ON Document (FolderLevel1);
CREATE INDEX IX_Document_Folder2       ON Document (FolderLevel2);
CREATE INDEX IX_Document_ModifiedTime  ON Document (ModifiedTime);
CREATE INDEX IX_Document_FileHash      ON Document (FileHashSHA256);

CREATE TRIGGER TR_Document_SetUpdatedAt
BEFORE UPDATE ON Document
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- =====================================================
-- 2. DocumentText: full extracted text per document
-- =====================================================
CREATE TABLE DocumentText
(
    DocID              BIGINT PRIMARY KEY,

    RawText            TEXT,
    CharacterCount     INT,
    WordCount          INT,

    ExtractedAt        TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_DocumentText_Document
        FOREIGN KEY (DocID)
        REFERENCES Document(DocID)
        ON DELETE CASCADE
);

-- =====================================================
-- 3. DocumentPageText: PDF/page-level text
-- =====================================================
CREATE TABLE DocumentPageText
(
    PageTextID         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    DocID              BIGINT NOT NULL,
    PageNo             INT NOT NULL,

    PageText           TEXT,
    CharacterCount     INT,

    CreatedAt          TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_DocumentPageText_Document
        FOREIGN KEY (DocID)
        REFERENCES Document(DocID)
        ON DELETE CASCADE,

    CONSTRAINT UX_DocumentPageText UNIQUE (DocID, PageNo)
);

CREATE INDEX IX_DocumentPageText_DocID ON DocumentPageText (DocID);

-- =====================================================
-- 4. DocumentSheetText: Excel sheet-level text
-- =====================================================
CREATE TABLE DocumentSheetText
(
    SheetTextID        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    DocID              BIGINT NOT NULL,
    SheetName          VARCHAR(255) NOT NULL,

    UsedRange          VARCHAR(100),
    RowCount           INT,
    ColumnCount        INT,

    SheetText          TEXT,
    CharacterCount     INT,

    CreatedAt          TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_DocumentSheetText_Document
        FOREIGN KEY (DocID)
        REFERENCES Document(DocID)
        ON DELETE CASCADE,

    CONSTRAINT UX_DocumentSheetText UNIQUE (DocID, SheetName)
);

CREATE INDEX IX_DocumentSheetText_DocID     ON DocumentSheetText (DocID);
CREATE INDEX IX_DocumentSheetText_SheetName ON DocumentSheetText (SheetName);

-- =====================================================
-- 5. DocumentChunk: chunks for retrieval / embedding
-- =====================================================
CREATE TABLE DocumentChunk
(
    ChunkID            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    DocID              BIGINT NOT NULL,

    ChunkNo            INT NOT NULL,
    ChunkSource        VARCHAR(50),       -- FullText / Page / Sheet / Manual

    PageNo             INT NULL,
    SheetName          VARCHAR(255) NULL,

    ChunkText          TEXT,

    StartPos           INT,
    EndPos             INT,

    CharacterCount     INT,
    TokenEstimate      INT,

    CreatedAt          TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_DocumentChunk_Document
        FOREIGN KEY (DocID)
        REFERENCES Document(DocID)
        ON DELETE CASCADE,

    CONSTRAINT UX_DocumentChunk UNIQUE (DocID, ChunkNo)
);

CREATE INDEX IX_DocumentChunk_DocID     ON DocumentChunk (DocID);
CREATE INDEX IX_DocumentChunk_Source    ON DocumentChunk (ChunkSource);
CREATE INDEX IX_DocumentChunk_PageNo    ON DocumentChunk (PageNo);
CREATE INDEX IX_DocumentChunk_SheetName ON DocumentChunk (SheetName);

-- =====================================================
-- 6. DocumentSummary: GPT document-level understanding
-- =====================================================
CREATE TABLE DocumentSummary
(
    DocID              BIGINT PRIMARY KEY,

    Title              VARCHAR(500),

    DocType            VARCHAR(100),
    Summary            TEXT,

    Keywords           TEXT,
    Topics             TEXT,
    Companies          TEXT,
    People             TEXT,
    Products           TEXT,
    Countries          TEXT,
    Years              TEXT,

    ImportanceScore    NUMERIC(4,2),

    GPTResponseJson    JSONB,

    GPTModel           VARCHAR(100),
    PromptVersion      VARCHAR(50),
    SummaryTime        TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_DocumentSummary_Document
        FOREIGN KEY (DocID)
        REFERENCES Document(DocID)
        ON DELETE CASCADE
);

CREATE INDEX IX_DocumentSummary_DocType    ON DocumentSummary (DocType);
CREATE INDEX IX_DocumentSummary_Importance ON DocumentSummary (ImportanceScore);

-- =====================================================
-- 7. DocumentEmbedding: optional Phase 2
-- =====================================================
-- Kept as JSONB to stay equivalent to the current MySQL design.
-- If pgvector is adopted later, replace EmbeddingVector with vector(n).
CREATE TABLE DocumentEmbedding
(
    EmbeddingID        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    ChunkID            BIGINT NOT NULL,

    EmbeddingModel     VARCHAR(100),
    EmbeddingVector    JSONB,

    VectorDimension    INT,
    CreatedAt          TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_DocumentEmbedding_DocumentChunk
        FOREIGN KEY (ChunkID)
        REFERENCES DocumentChunk(ChunkID)
        ON DELETE CASCADE,

    CONSTRAINT UX_DocumentEmbedding UNIQUE (ChunkID, EmbeddingModel)
);

CREATE INDEX IX_DocumentEmbedding_ChunkID ON DocumentEmbedding (ChunkID);

-- =====================================================
-- 8. QuestionLog
-- Legacy QuestionLog is intentionally omitted; AgentExecutionLog is used instead.
-- =====================================================

-- =====================================================
-- 9. ProcessLog: batch processing log
-- =====================================================
CREATE TABLE ProcessLog
(
    LogID              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    DocID              BIGINT NULL,

    ProcessName        VARCHAR(100),
    Status             VARCHAR(30),

    StartTime          TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    EndTime            TIMESTAMP WITHOUT TIME ZONE NULL,

    Message            TEXT,

    CONSTRAINT FK_ProcessLog_Document
        FOREIGN KEY (DocID)
        REFERENCES Document(DocID)
        ON DELETE SET NULL
);

CREATE INDEX IX_ProcessLog_DocID       ON ProcessLog (DocID);
CREATE INDEX IX_ProcessLog_ProcessName ON ProcessLog (ProcessName);
CREATE INDEX IX_ProcessLog_Status      ON ProcessLog (Status);
CREATE INDEX IX_ProcessLog_StartTime   ON ProcessLog (StartTime);

-- =====================================================
-- 10. AgentSetting
-- =====================================================
CREATE TABLE AgentSetting
(
    SettingName        VARCHAR(100) PRIMARY KEY,
    SettingValue       TEXT,
    UpdatedAt          TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER TR_AgentSetting_SetUpdatedAt
BEFORE UPDATE ON AgentSetting
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- =====================================================
-- Default settings
-- =====================================================
INSERT INTO AgentSetting (SettingName, SettingValue)
VALUES
('TopKDocuments', '20'),
('MaxSingleDocumentChunks', '80'),
('MaxSingleDocumentChunkChars', '3000');

-- =====================================================
-- Useful views
-- =====================================================
CREATE OR REPLACE VIEW vw_DocumentStatus AS
SELECT
    Extension,
    ParseStatus,
    COUNT(*) AS FileCount,
    ROUND(SUM(FileSizeBytes)::NUMERIC / 1024 / 1024, 2) AS TotalSizeMB
FROM Document
GROUP BY Extension, ParseStatus;

CREATE OR REPLACE VIEW vw_DocumentWithSummary AS
SELECT
    d.DocID,
    d.FullPath,
    d.RelativePath,
    d.FolderLevel1,
    d.FolderLevel2,
    d.FolderLevel3,
    d.FileName,
    d.Extension,
    d.FileSizeBytes,
    d.ModifiedTime,
    d.ParseStatus,
    s.Title,
    s.DocType,
    s.Summary,
    s.Keywords,
    s.Topics,
    s.Companies,
    s.Products,
    s.Countries,
    s.Years,
    s.ImportanceScore,
    s.GPTModel,
    s.SummaryTime
FROM Document d
LEFT JOIN DocumentSummary s
    ON d.DocID = s.DocID;

-- =====================================================
-- Full-text and multilingual substring indexes
-- =====================================================
CREATE INDEX FT_DocumentChunk_ChunkText
ON DocumentChunk
USING GIN (to_tsvector('simple', COALESCE(ChunkText, '')));

CREATE INDEX IX_DocumentChunk_ChunkText_Trgm
ON DocumentChunk
USING GIN (ChunkText gin_trgm_ops);

-- =====================================================================
-- Unified agent execution log
-- =====================================================================

CREATE TABLE AgentExecutionLog
(
    -- Identity
    ExecutionID                CHAR(36)          NOT NULL,
    ThreadID                   CHAR(36)          NULL,

    RequestStartedAt           TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL
                               DEFAULT CURRENT_TIMESTAMP(3),
    RequestCompletedAt         TIMESTAMP(3) WITHOUT TIME ZONE NULL,

    -- User request
    UserQuestion               TEXT              NOT NULL,
    UserCommand                VARCHAR(50)       NULL,
    Username                   VARCHAR(255)      NULL,
    CallingFrom                VARCHAR(255)      NULL,

    -- Router
    RouterIntent               VARCHAR(50)       NULL,
    RouterJSON                 JSONB             NULL,
    RouterSearchQuery          TEXT              NULL,
    RouterTopicTitle           VARCHAR(500)      NULL,
    ForceNewSearch             SMALLINT          NULL,

    -- Execution mode
    SearchMode                 VARCHAR(50)       NULL,
    PresentationMode           VARCHAR(50)       NULL,

    -- SQL execution
    GeneratedSQL               TEXT              NULL,
    SQLParameters              JSONB             NULL,
    RowsReturned               INT               NULL,

    SQLStartedAt               TIMESTAMP(3) WITHOUT TIME ZONE NULL,
    SQLCompletedAt             TIMESTAMP(3) WITHOUT TIME ZONE NULL,
    SQLElapsedMS               INT               NULL,
    SQLTraceJSON               JSONB             NULL,

    -- Search / retrieval
    SearchQuery                TEXT              NULL,
    NewSearch                  SMALLINT          NULL,

    MatchedChunks              INT               NULL,
    ChunkLimit                 INT               NULL,
    ChunksRetrieved            INT               NULL,
    UniqueDocumentsMatched     INT               NULL,
    DocumentsSent              INT               NULL,
    ChunksSentToGPT            INT               NULL,

    MaxChunksPerDoc            INT               NULL,
    MaxCharsPerChunk           INT               NULL,

    DocumentRankingMethod      VARCHAR(100)      NULL,
    RetrievalStatsJSON         JSONB             NULL,

    -- Original RAG log detail
    DocumentsUsed              JSONB             NULL,
    ChunksUsed                 JSONB             NULL,

    -- GPT / LLM usage
    -- SMALLINT preserves the existing Python 0/1 contract.
    GPTUsed                     SMALLINT          NOT NULL DEFAULT 0,
    GPTModel                    VARCHAR(150)      NULL,
    GPTPurpose                  VARCHAR(100)      NULL,

    PromptChars                 INT               NULL,
    PromptTokens                INT               NULL,
    CompletionTokens            INT               NULL,
    TotalTokens                 INT               NULL,

    GPTStartedAt                TIMESTAMP(3) WITHOUT TIME ZONE NULL,
    GPTCompletedAt              TIMESTAMP(3) WITHOUT TIME ZONE NULL,
    GPTElapsedMS                INT               NULL,

    GPTUsageJSON                JSONB             NULL,
    PromptSample                TEXT              NULL,

    -- Final answer
    FinalAnswer                 TEXT              NULL,
    AnswerChars                 INT               NULL,

    -- Status and timing
    ExecutionStatus             VARCHAR(30)       NOT NULL DEFAULT 'Success',
    ElapsedMS                   INT               NULL,

    -- Errors
    ErrorStage                  VARCHAR(50)       NULL,
    ErrorType                   VARCHAR(255)      NULL,
    ErrorMessage                TEXT              NULL,
    ErrorTraceback              TEXT              NULL,

    -- Audit
    CreatedAt                   TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL
                               DEFAULT CURRENT_TIMESTAMP(3),
    UpdatedAt                   TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL
                               DEFAULT CURRENT_TIMESTAMP(3),

    -- Constraints
    CONSTRAINT PK_AgentExecutionLog
        PRIMARY KEY (ExecutionID),

    CONSTRAINT CK_AgentExecutionLog_Status
        CHECK
        (
            ExecutionStatus IN
            (
                'Success', 'Failed', 'NoResults', 'Partial', 'Cancelled',
                'Ambiguous', 'EmptyForcedRouteQuery', 'NoDocumentBound'
            )
        ),

    CONSTRAINT CK_AgentExecutionLog_GPTUsed
        CHECK (GPTUsed IN (0, 1)),

    CONSTRAINT CK_AgentExecutionLog_NewSearch
        CHECK (NewSearch IS NULL OR NewSearch IN (0, 1)),

    CONSTRAINT CK_AgentExecutionLog_ForceNewSearch
        CHECK (ForceNewSearch IS NULL OR ForceNewSearch IN (0, 1))
);

-- UpdatedAt is maintained by the shared set_updated_at() function.
CREATE TRIGGER TR_AgentExecutionLog_SetUpdatedAt
BEFORE UPDATE ON AgentExecutionLog
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- =========================================================
-- Indexes
-- =========================================================
CREATE INDEX IX_AgentExecutionLog_RequestStartedAt
    ON AgentExecutionLog (RequestStartedAt DESC);

CREATE INDEX IX_AgentExecutionLog_Thread
    ON AgentExecutionLog (ThreadID, RequestStartedAt DESC);

CREATE INDEX IX_AgentExecutionLog_Intent
    ON AgentExecutionLog (RouterIntent, RequestStartedAt DESC);

CREATE INDEX IX_AgentExecutionLog_SearchMode
    ON AgentExecutionLog (SearchMode, RequestStartedAt DESC);

CREATE INDEX IX_AgentExecutionLog_Status
    ON AgentExecutionLog (ExecutionStatus, RequestStartedAt DESC);

CREATE INDEX IX_AgentExecutionLog_GPTUsed
    ON AgentExecutionLog (GPTUsed, RequestStartedAt DESC);

-- Expression index on the first 255 characters of SearchQuery.
CREATE INDEX IX_AgentExecutionLog_SearchQuery
    ON AgentExecutionLog ((LEFT(SearchQuery, 255)));

-- Optional JSONB GIN indexes can be added later if you begin filtering
-- heavily inside RouterJSON / DocumentsUsed / ChunksUsed.

-- =========================================================
-- View 1: Recent agent activity
-- =========================================================
CREATE OR REPLACE VIEW vw_AgentExecutionLog_Recent AS
SELECT
    ExecutionID,
    ThreadID,
    RequestStartedAt,
    RequestCompletedAt,
    UserQuestion,
    UserCommand,
    RouterIntent,
    RouterSearchQuery,
    RouterTopicTitle,
    SearchMode,
    PresentationMode,
    SearchQuery,
    GeneratedSQL,
    SQLParameters,
    RowsReturned,
    MatchedChunks,
    ChunkLimit,
    ChunksRetrieved,
    UniqueDocumentsMatched,
    DocumentsSent,
    ChunksSentToGPT,
    GPTUsed,
    GPTPurpose,
    GPTModel,
    PromptTokens,
    CompletionTokens,
    TotalTokens,
    SQLElapsedMS,
    GPTElapsedMS,
    ElapsedMS,
    ExecutionStatus,
    ErrorStage,
    ErrorType,
    LEFT(ErrorMessage, 1000) AS ErrorMessageSample,
    LEFT(FinalAnswer, 2000) AS FinalAnswerSample
FROM AgentExecutionLog
ORDER BY RequestStartedAt DESC;

-- =========================================================
-- View 2: Daily usage summary
-- =========================================================
CREATE OR REPLACE VIEW vw_AgentExecutionLog_DailyStats AS
SELECT
    RequestStartedAt::DATE AS ExecutionDate,
    COUNT(*) AS RequestCount,
    SUM(CASE WHEN ExecutionStatus = 'Success'   THEN 1 ELSE 0 END) AS SuccessCount,
    SUM(CASE WHEN ExecutionStatus = 'Failed'    THEN 1 ELSE 0 END) AS FailedCount,
    SUM(CASE WHEN ExecutionStatus = 'NoResults' THEN 1 ELSE 0 END) AS NoResultsCount,
    SUM(CASE WHEN GPTUsed = 1                   THEN 1 ELSE 0 END) AS GPTRequestCount,
    SUM(COALESCE(PromptTokens, 0)) AS PromptTokens,
    SUM(COALESCE(CompletionTokens, 0)) AS CompletionTokens,
    SUM(COALESCE(TotalTokens, 0)) AS TotalTokens,
    ROUND(AVG(ElapsedMS), 0) AS AverageElapsedMS,
    MAX(ElapsedMS) AS MaximumElapsedMS,
    ROUND(AVG(SQLElapsedMS), 0) AS AverageSQLElapsedMS,
    ROUND(AVG(GPTElapsedMS), 0) AS AverageGPTElapsedMS
FROM AgentExecutionLog
GROUP BY RequestStartedAt::DATE;

-- =========================================================
-- View 3: Intent and search mode performance
-- =========================================================
CREATE OR REPLACE VIEW vw_AgentExecutionLog_IntentStats AS
SELECT
    COALESCE(RouterIntent, '(No Intent)') AS RouterIntent,
    COALESCE(SearchMode, '(No Search Mode)') AS SearchMode,
    COUNT(*) AS RequestCount,
    SUM(CASE WHEN ExecutionStatus = 'Success'   THEN 1 ELSE 0 END) AS SuccessCount,
    SUM(CASE WHEN ExecutionStatus = 'Failed'    THEN 1 ELSE 0 END) AS FailedCount,
    SUM(CASE WHEN ExecutionStatus = 'NoResults' THEN 1 ELSE 0 END) AS NoResultsCount,
    ROUND(AVG(RowsReturned), 1) AS AverageRowsReturned,
    ROUND(AVG(ElapsedMS), 0) AS AverageElapsedMS,
    ROUND(AVG(TotalTokens), 0) AS AverageTokens
FROM AgentExecutionLog
GROUP BY
    COALESCE(RouterIntent, '(No Intent)'),
    COALESCE(SearchMode, '(No Search Mode)');

-- =========================================================
-- View 4: Error report
-- =========================================================
CREATE OR REPLACE VIEW vw_AgentExecutionLog_Errors AS
SELECT
    ExecutionID,
    ThreadID,
    RequestStartedAt,
    UserQuestion,
    RouterIntent,
    SearchMode,
    ErrorStage,
    ErrorType,
    ErrorMessage,
    ErrorTraceback,
    ElapsedMS
FROM AgentExecutionLog
WHERE ExecutionStatus = 'Failed'
ORDER BY RequestStartedAt DESC;

-- =========================================================
-- View 5: RAG usage and document retrieval summary
-- =========================================================
CREATE OR REPLACE VIEW vw_AgentExecutionLog_RAGStats AS
SELECT
    ExecutionID,
    ThreadID,
    RequestStartedAt,
    UserQuestion,
    RouterIntent,
    SearchQuery,
    MatchedChunks,
    ChunkLimit,
    ChunksRetrieved,
    UniqueDocumentsMatched,
    DocumentsSent,
    ChunksSentToGPT,
    DocumentRankingMethod,
    PromptTokens,
    CompletionTokens,
    TotalTokens,
    ElapsedMS,
    ExecutionStatus
FROM AgentExecutionLog
WHERE SearchMode = 'RAG_FULLTEXT'
ORDER BY RequestStartedAt DESC;

-- =====================================================================
-- Complete the atomic schema creation
-- =====================================================================
COMMIT;

-- =====================================================================
-- Validation
-- =====================================================================
SELECT extname, extversion
FROM pg_extension
WHERE extname = 'pg_trgm';

SELECT tablename
FROM pg_catalog.pg_tables
WHERE schemaname = 'public'
ORDER BY tablename;

SELECT indexname, tablename
FROM pg_indexes
WHERE schemaname = 'public'
ORDER BY tablename, indexname;

